//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("0.3.3")]
[assembly: AssemblyFileVersion("0.3.3")]
[assembly: AssemblyInformationalVersion("0.3.3")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2019 Phillip Sharpe")]

